version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - NEXT_PUBLIC_APP_URL=${NEXT_PUBLIC_APP_URL:-http://localhost:3000}
      - NEXT_PUBLIC_ENABLE_WEBCONTAINER=${NEXT_PUBLIC_ENABLE_WEBCONTAINER:-true}
      # Add your API keys here
      # - GEMINI_API_KEY=${GEMINI_API_KEY}
    restart: unless-stopped
    # Add healthcheck to ensure the application is running properly
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    # Set resource limits to prevent container from using too much resources
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G